/*FUNCTIONS DECLARATIONS*/

/*TFT MODULE FUNCTIONS DECLARATION*/
void TFT_INIT();
void TFT_DRAW_LOGO();
void TFT_DRAW_LINE();
void TFT_PRINT_DIRECTION(String, byte);
void TFT_PRINT_ERROR(String);
void TFT_PRINT_ENCODERS_STATUS(int, int);
void TFT_PRINT_SPEED(byte , byte);
void TFT_PRINT_DISTANCE(long);
void TFT_PRINT_TEXT(String, byte, uint16_t, byte, byte);
void TFT_PRINT_KEY_PRESSED(byte);
void TFT_CLEAR_ERROR_AREA();
void TFT_CLEAR_WORK_AREA();
void TFT_FUNC_AREA();

/*MOTORS MODULE FUNCTIONS DECLARATION*/
void MOTORS_SETUP();
void ROBI_STOP();
void ROBI_FORWARD(byte, byte);
void ROBI_BACK(byte, byte);

/*IRREMOTE MODULE FUNCTIONS DECLARATION*/
void IRREMOTE_INIT();
void CHECK_IR();
//old
//boolean IRREMOTE_RECEIVE();
//void IRREMOTE_RESUME();
//byte IRREMOTE_TRANSLATE_IR();

/*ULTRASONIC MODULE FUNCTIONS DECLARATION*/
void ULTRASONIC_INIT();
long ULTRASONIC_1X_PING();
int ULTRASONIC_3X_PING();
boolean ULTRASONIC_TEST();
int ULTRASONIC_1X_PING_2();

/*SERVO MODULE FUNCTIONS DECLARATION*/
void SERVO_INIT();
void SERVO_TEST();
void SERVO_TURN(int);

/*ENCODERS MODULE FUNCTIONS DECLARATION*/
void ENCODERS_SETUP();
int ENCODERS_GET_LEFT_COUNT();
int ENCODERS_GET_RIGHT_COUNT();

/*WALL MODULE FUNCTIONS DECLARATION*/
void WALL_MODULE_INIT();
byte WALL_MODULE_DETECT();

/*BUZZER MODULE FUNCTIONS DECLARATION*/
void BUZZER_MODULE_INIT();
void BUZZER_MODULE_TEST();
void BUZZER_MODULE_BEEP(int);
void BUZZER_MODULE_BEEP_ON();
void BUZZER_MODULE_BEEP_OFF();

/*VOICE MODULE FUNCTIONS DECLARATION*/
boolean VOICE_INIT();
byte VOICE_DETECT();

/*LINE MODULE FUNCTIONS DECLARATION*/
void LINE_MODULE_INIT();
void LINE_MODULE_READ();
void LINE_MODULE_STATUS_SERIAL_PRINT();
void LINE_MODULE_GET_UPDATE_STATUS();

/*MICROPHONE MODULE FUNCTIONS DECLARATION*/
void MIC_MODULE_INIT();
boolean MIC_MODULE_DIGITAL_DETECT();
int MIC_MODULE_ANALOG_DETECT();
