//MODE2:DISCOVER LOGICS FILE
	#ifdef TFT_MODULE
		TFT_PRINT_DIRECTION("DISCVR", 3);
	#endif

WALL_STATE = WALL_MODULE_DETECT();

// check left and right wall switches	
if (0 != WALL_STATE){BUZZER_MODULE_BEEP_ON();}
else {BUZZER_MODULE_BEEP_OFF();}
// check switch on line module (CLP)
if (1 == CLP_STATUS){BUZZER_MODULE_BEEP_ON();}
else {BUZZER_MODULE_BEEP_OFF();}


	//SOME WALL MODULE TEST CODE
	if (1 == CLP_STATUS){
		TFT_PRINT_ERROR("CENTER WALL DETECTED!");
			ROBI_STOP();
	}
	if (1 == WALL_STATE){
		//TFT_PRINT_DIRECTION(" LEFT WALL", 2);
		TFT_PRINT_ERROR("LEFT WALL DETECTED!");
			ROBI_STOP();
	}
	if (2 == WALL_STATE){
		//TFT_PRINT_DIRECTION("RIGHT WALL", 2);
		TFT_PRINT_ERROR("RIGHT WALL DETECTED!");
			ROBI_STOP();
	}
	if (3 == WALL_STATE){
		//TFT_PRINT_DIRECTION("BOTH WALLS", 2);
		TFT_PRINT_ERROR("BOTH WALLS DETECTED!");
			ROBI_STOP();
	}
	if (0 == WALL_STATE){
		TFT_CLEAR_ERROR_AREA();
		ROBI_FORWARD(120,120);
	}


	//PINGING
		//SERVO LEFT
			SERVO_TURN(45);
				delay(200); //WAIT
			LEFT_PING = ULTRASONIC_1X_PING();
		//SERVO CENTER
			SERVO_TURN(90);
				delay(100); //WAIT
			CENTER_PING = ULTRASONIC_1X_PING();
		//SERVO RIGHT
			SERVO_TURN(135);
				delay(100); //WAIT
			RIGHT_PING = ULTRASONIC_1X_PING();

	//CALCULATE
		if (CENTER_PING < 20){

			ROBI_BACK(70,70);
			//delay(400);

		}
		else {

			if (CENTER_PING > 80){ROBI_FORWARD(120,120);}
			else if (LEFT_PING > RIGHT_PING){ ROBI_FORWARD(25,200);}
			else { ROBI_FORWARD(200,25);}

		}
